void downMove(int moves);
void fire();
void fireAll();
void homeServos();
void initializeServos();
void leftMove(int moves);
void nodHeadYes(int moves = 3);
void rightMove(int moves);
void shakeHeadNo(int moves = 3);
void upMove(int moves);